POST http://localhost:3001/api/sms/send
Content-Type: application/json

{
  
  "applicationId": "APP_009097",
  "password": "password",
  "message": "Hello",
  "destinationAddresses": [
    "tel:94702029244"
  ],
  "sourceAddress": "tel:94710988816",
  "deliveryStatusRequest": "1",
  "encoding": "0"
  
  
}

HTTP/1.1 502  - Bad Gateway
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
date: Mon, 29 Sep 2025 06:06:57 GMT
connection: close
transfer-encoding: chunked